"""initial schema baseline

Revision ID: 5830d6e42a5b
Revises:
Create Date: 2026-09-11 16:55:25.260127

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5830d6e42a5b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clubs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("settings_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clubs")),
    )
    op.create_index(op.f("ix_clubs_slug"), "clubs", ["slug"], unique=True)
    op.create_table(
        "club_modules",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("module_key", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_club_modules_club_id_clubs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_club_modules")),
        sa.UniqueConstraint("club_id", "module_key", name="uq_club_modules_club_key"),
    )
    op.create_index(op.f("ix_club_modules_club_id"), "club_modules", ["club_id"], unique=False)
    op.create_table(
        "competition_sources",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("adapter_key", sa.String(length=64), nullable=False),
        sa.Column("config_json", sa.JSON(), nullable=False),
        sa.Column("attribution", sa.String(length=512), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_competition_sources_club_id_clubs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_sources")),
    )
    op.create_index(
        op.f("ix_competition_sources_adapter_key"),
        "competition_sources",
        ["adapter_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_competition_sources_club_id"), "competition_sources", ["club_id"], unique=False
    )
    op.create_table(
        "coupons",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("percent_off", sa.Integer(), nullable=True),
        sa.Column("amount_off_cents", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_redemptions", sa.Integer(), nullable=True),
        sa.Column("redeemed_count", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], name=op.f("fk_coupons_club_id_clubs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupons")),
        sa.UniqueConstraint("club_id", "code", name="uq_coupons_club_code"),
    )
    op.create_index(op.f("ix_coupons_club_id"), "coupons", ["club_id"], unique=False)
    op.create_index(op.f("ix_coupons_code"), "coupons", ["code"], unique=False)
    op.create_table(
        "meal_templates",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("day_type", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("macros_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_meal_templates_club_id_clubs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meal_templates")),
    )
    op.create_index(op.f("ix_meal_templates_club_id"), "meal_templates", ["club_id"], unique=False)
    op.create_index(
        op.f("ix_meal_templates_day_type"), "meal_templates", ["day_type"], unique=False
    )
    op.create_table(
        "merch_categories",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_merch_categories_club_id_clubs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merch_categories")),
        sa.UniqueConstraint("club_id", "slug", name="uq_merch_categories_club_slug"),
    )
    op.create_index(
        op.f("ix_merch_categories_club_id"), "merch_categories", ["club_id"], unique=False
    )
    op.create_index(op.f("ix_merch_categories_slug"), "merch_categories", ["slug"], unique=False)
    op.create_table(
        "promotions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("percent_off", sa.Integer(), nullable=True),
        sa.Column("amount_off_cents", sa.Integer(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_redemptions", sa.Integer(), nullable=True),
        sa.Column("redeemed_count", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_promotions_club_id_clubs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promotions")),
        sa.UniqueConstraint("club_id", "code", name="uq_promotions_club_code"),
    )
    op.create_index(op.f("ix_promotions_club_id"), "promotions", ["club_id"], unique=False)
    op.create_index(op.f("ix_promotions_code"), "promotions", ["code"], unique=False)
    op.create_table(
        "registration_forms",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("season", sa.String(length=64), nullable=True),
        sa.Column("fields_json", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_registration_forms_club_id_clubs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registration_forms")),
    )
    op.create_index(
        op.f("ix_registration_forms_club_id"), "registration_forms", ["club_id"], unique=False
    )
    op.create_table(
        "shipping_configs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("flat_rate_cents", sa.Integer(), nullable=False),
        sa.Column("free_over_cents", sa.Integer(), nullable=True),
        sa.Column("regions_json", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_shipping_configs_club_id_clubs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shipping_configs")),
    )
    op.create_index(
        op.f("ix_shipping_configs_club_id"), "shipping_configs", ["club_id"], unique=False
    )
    op.create_table(
        "tax_configs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("rate_bps", sa.Integer(), nullable=False),
        sa.Column("region", sa.String(length=64), nullable=True),
        sa.Column("inclusive", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_tax_configs_club_id_clubs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tax_configs")),
    )
    op.create_index(op.f("ix_tax_configs_club_id"), "tax_configs", ["club_id"], unique=False)
    op.create_table(
        "teams",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sport", sa.String(length=64), nullable=False),
        sa.Column("age_group", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], name=op.f("fk_teams_club_id_clubs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
    )
    op.create_index(op.f("ix_teams_club_id"), "teams", ["club_id"], unique=False)
    op.create_table(
        "training_templates",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("drills_json", sa.JSON(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_training_templates_club_id_clubs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_templates")),
    )
    op.create_index(
        op.f("ix_training_templates_club_id"), "training_templates", ["club_id"], unique=False
    )
    op.create_index(
        op.f("ix_training_templates_role"), "training_templates", ["role"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], name=op.f("fk_users_club_id_clubs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_club_id"), "users", ["club_id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=True),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("provider_event_id", sa.String(length=255), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_webhook_events_club_id_clubs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
    )
    op.create_index(op.f("ix_webhook_events_club_id"), "webhook_events", ["club_id"], unique=False)
    op.create_index(
        op.f("ix_webhook_events_provider_event_id"),
        "webhook_events",
        ["provider_event_id"],
        unique=True,
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_audit_logs_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_logs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(op.f("ix_audit_logs_club_id"), "audit_logs", ["club_id"], unique=False)
    op.create_table(
        "carts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], name=op.f("fk_carts_club_id_clubs")),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_carts_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carts")),
    )
    op.create_index(op.f("ix_carts_club_id"), "carts", ["club_id"], unique=False)
    op.create_index(op.f("ix_carts_status"), "carts", ["status"], unique=False)
    op.create_index(op.f("ix_carts_user_id"), "carts", ["user_id"], unique=False)
    op.create_table(
        "competition_fixtures",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=32), nullable=True),
        sa.Column("team_id", sa.String(length=32), nullable=True),
        sa.Column("external_ref", sa.String(length=255), nullable=True),
        sa.Column("competition_name", sa.String(length=255), nullable=True),
        sa.Column("home_team", sa.String(length=255), nullable=False),
        sa.Column("away_team", sa.String(length=255), nullable=False),
        sa.Column("kickoff_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("venue", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_competition_fixtures_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["competition_sources.id"],
            name=op.f("fk_competition_fixtures_source_id_competition_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_competition_fixtures_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_fixtures")),
    )
    op.create_index(
        op.f("ix_competition_fixtures_club_id"), "competition_fixtures", ["club_id"], unique=False
    )
    op.create_index(
        op.f("ix_competition_fixtures_external_ref"),
        "competition_fixtures",
        ["external_ref"],
        unique=False,
    )
    op.create_index(
        op.f("ix_competition_fixtures_source_id"),
        "competition_fixtures",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "competition_standings",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=32), nullable=True),
        sa.Column("competition_name", sa.String(length=255), nullable=True),
        sa.Column("season", sa.String(length=64), nullable=True),
        sa.Column("team_name", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("played", sa.Integer(), nullable=False),
        sa.Column("won", sa.Integer(), nullable=False),
        sa.Column("drawn", sa.Integer(), nullable=False),
        sa.Column("lost", sa.Integer(), nullable=False),
        sa.Column("goals_for", sa.Integer(), nullable=False),
        sa.Column("goals_against", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_competition_standings_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["competition_sources.id"],
            name=op.f("fk_competition_standings_source_id_competition_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competition_standings")),
    )
    op.create_index(
        op.f("ix_competition_standings_club_id"), "competition_standings", ["club_id"], unique=False
    )
    op.create_index(
        op.f("ix_competition_standings_source_id"),
        "competition_standings",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "fee_rules",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=True),
        sa.Column("age_group", sa.String(length=64), nullable=True),
        sa.Column("team_id", sa.String(length=32), nullable=True),
        sa.Column("season", sa.String(length=64), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("max_installments", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], name=op.f("fk_fee_rules_club_id_clubs")),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name=op.f("fk_fee_rules_team_id_teams")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fee_rules")),
    )
    op.create_index(op.f("ix_fee_rules_club_id"), "fee_rules", ["club_id"], unique=False)
    op.create_table(
        "matches",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("team_id", sa.String(length=32), nullable=False),
        sa.Column("opponent", sa.String(length=255), nullable=False),
        sa.Column("sport", sa.String(length=64), nullable=False),
        sa.Column("kickoff_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("venue", sa.String(length=255), nullable=True),
        sa.Column("period_config_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], name=op.f("fk_matches_club_id_clubs")),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name=op.f("fk_matches_team_id_teams")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
    )
    op.create_index(op.f("ix_matches_club_id"), "matches", ["club_id"], unique=False)
    op.create_index(op.f("ix_matches_team_id"), "matches", ["team_id"], unique=False)
    op.create_table(
        "merch_products",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("category_id", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("base_price_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("image_storage_key", sa.String(length=512), nullable=True),
        sa.Column("external_ref", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["merch_categories.id"],
            name=op.f("fk_merch_products_category_id_merch_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_merch_products_club_id_clubs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merch_products")),
        sa.UniqueConstraint("club_id", "slug", name="uq_merch_products_club_slug"),
    )
    op.create_index(
        op.f("ix_merch_products_category_id"), "merch_products", ["category_id"], unique=False
    )
    op.create_index(op.f("ix_merch_products_club_id"), "merch_products", ["club_id"], unique=False)
    op.create_index(op.f("ix_merch_products_slug"), "merch_products", ["slug"], unique=False)
    op.create_table(
        "players",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("team_id", sa.String(length=32), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("jersey_number", sa.Integer(), nullable=True),
        sa.Column("position", sa.String(length=64), nullable=True),
        sa.Column("external_ref", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], name=op.f("fk_players_club_id_clubs")),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name=op.f("fk_players_team_id_teams")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
    )
    op.create_index(op.f("ix_players_club_id"), "players", ["club_id"], unique=False)
    op.create_index(op.f("ix_players_team_id"), "players", ["team_id"], unique=False)
    op.create_table(
        "plays",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("team_id", sa.String(length=32), nullable=True),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("diagram_storage_key", sa.String(length=512), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_play_id", sa.String(length=32), nullable=True),
        sa.Column("tags_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], name=op.f("fk_plays_club_id_clubs")),
        sa.ForeignKeyConstraint(
            ["parent_play_id"], ["plays.id"], name=op.f("fk_plays_parent_play_id_plays")
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], name=op.f("fk_plays_team_id_teams")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plays")),
    )
    op.create_index(op.f("ix_plays_category"), "plays", ["category"], unique=False)
    op.create_index(op.f("ix_plays_club_id"), "plays", ["club_id"], unique=False)
    op.create_index(op.f("ix_plays_parent_play_id"), "plays", ["parent_play_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("jti", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
    )
    op.create_index(op.f("ix_refresh_tokens_jti"), "refresh_tokens", ["jti"], unique=True)
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "registrations",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("form_id", sa.String(length=32), nullable=True),
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("registrant_type", sa.String(length=16), nullable=False),
        sa.Column("registrant_name", sa.String(length=255), nullable=False),
        sa.Column("registrant_dob", sa.Date(), nullable=True),
        sa.Column("family_group_id", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("answers_json", sa.JSON(), nullable=False),
        sa.Column("consent_json", sa.JSON(), nullable=False),
        sa.Column("medical_flags_json", sa.JSON(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_registrations_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"], ["users.id"], name=op.f("fk_registrations_decided_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["form_id"],
            ["registration_forms.id"],
            name=op.f("fk_registrations_form_id_registration_forms"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_registrations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registrations")),
    )
    op.create_index(op.f("ix_registrations_club_id"), "registrations", ["club_id"], unique=False)
    op.create_index(
        op.f("ix_registrations_family_group_id"), "registrations", ["family_group_id"], unique=False
    )
    op.create_index(op.f("ix_registrations_form_id"), "registrations", ["form_id"], unique=False)
    op.create_index(op.f("ix_registrations_status"), "registrations", ["status"], unique=False)
    op.create_table(
        "training_plans",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("team_id", sa.String(length=32), nullable=True),
        sa.Column("template_id", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("starts_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("weeks", sa.Integer(), nullable=False),
        sa.Column("periodization_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_training_plans_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_training_plans_team_id_teams")
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["training_templates.id"],
            name=op.f("fk_training_plans_template_id_training_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_plans")),
    )
    op.create_index(op.f("ix_training_plans_club_id"), "training_plans", ["club_id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("team_id", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_user_roles_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_user_roles_team_id_teams")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_roles")),
    )
    op.create_index(op.f("ix_user_roles_club_id"), "user_roles", ["club_id"], unique=False)
    op.create_index(op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("match_id", sa.String(length=32), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("meta_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], name=op.f("fk_artifacts_club_id_clubs")),
        sa.ForeignKeyConstraint(
            ["match_id"], ["matches.id"], name=op.f("fk_artifacts_match_id_matches")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
    )
    op.create_index(op.f("ix_artifacts_club_id"), "artifacts", ["club_id"], unique=False)
    op.create_index(op.f("ix_artifacts_kind"), "artifacts", ["kind"], unique=False)
    op.create_index(op.f("ix_artifacts_match_id"), "artifacts", ["match_id"], unique=False)
    op.create_table(
        "athlete_profiles",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("player_id", sa.String(length=32), nullable=False),
        sa.Column("units", sa.String(length=16), nullable=False),
        sa.Column("height_cm", sa.Float(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("dietary_flags_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_athlete_profiles_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_athlete_profiles_player_id_players")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_athlete_profiles")),
        sa.UniqueConstraint("club_id", "player_id", name="uq_athlete_profiles_club_player"),
    )
    op.create_index(
        op.f("ix_athlete_profiles_club_id"), "athlete_profiles", ["club_id"], unique=False
    )
    op.create_index(
        op.f("ix_athlete_profiles_player_id"), "athlete_profiles", ["player_id"], unique=False
    )
    op.create_table(
        "cart_items",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("cart_id", sa.String(length=32), nullable=False),
        sa.Column("product_ref", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("unit_price_cents", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("meta_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cart_id"], ["carts.id"], name=op.f("fk_cart_items_cart_id_carts")
        ),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_cart_items_club_id_clubs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_items")),
    )
    op.create_index(op.f("ix_cart_items_cart_id"), "cart_items", ["cart_id"], unique=False)
    op.create_index(op.f("ix_cart_items_club_id"), "cart_items", ["club_id"], unique=False)
    op.create_table(
        "coach_notes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("player_id", sa.String(length=32), nullable=False),
        sa.Column("plan_id", sa.String(length=32), nullable=True),
        sa.Column("author_user_id", sa.String(length=32), nullable=True),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_user_id"], ["users.id"], name=op.f("fk_coach_notes_author_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_coach_notes_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["training_plans.id"], name=op.f("fk_coach_notes_plan_id_training_plans")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_coach_notes_player_id_players")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coach_notes")),
    )
    op.create_index(op.f("ix_coach_notes_club_id"), "coach_notes", ["club_id"], unique=False)
    op.create_index(op.f("ix_coach_notes_player_id"), "coach_notes", ["player_id"], unique=False)
    op.create_table(
        "hydration_reminders",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("player_id", sa.String(length=32), nullable=True),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("time_of_day", sa.String(length=5), nullable=False),
        sa.Column("interval_minutes", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_hydration_reminders_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_hydration_reminders_player_id_players")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hydration_reminders")),
    )
    op.create_index(
        op.f("ix_hydration_reminders_club_id"), "hydration_reminders", ["club_id"], unique=False
    )
    op.create_index(
        op.f("ix_hydration_reminders_player_id"), "hydration_reminders", ["player_id"], unique=False
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("registration_id", sa.String(length=32), nullable=True),
        sa.Column("fee_rule_id", sa.String(length=32), nullable=True),
        sa.Column("coupon_id", sa.String(length=32), nullable=True),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("installments", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("meta_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], name=op.f("fk_invoices_club_id_clubs")),
        sa.ForeignKeyConstraint(
            ["coupon_id"], ["coupons.id"], name=op.f("fk_invoices_coupon_id_coupons")
        ),
        sa.ForeignKeyConstraint(
            ["fee_rule_id"], ["fee_rules.id"], name=op.f("fk_invoices_fee_rule_id_fee_rules")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_invoices_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
    )
    op.create_index(op.f("ix_invoices_club_id"), "invoices", ["club_id"], unique=False)
    op.create_index(
        op.f("ix_invoices_registration_id"), "invoices", ["registration_id"], unique=False
    )
    op.create_index(op.f("ix_invoices_status"), "invoices", ["status"], unique=False)
    op.create_table(
        "merch_product_variants",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("product_id", sa.String(length=32), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("size", sa.String(length=32), nullable=True),
        sa.Column("color", sa.String(length=32), nullable=True),
        sa.Column("price_cents", sa.Integer(), nullable=True),
        sa.Column("inventory_qty", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_merch_product_variants_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["merch_products.id"],
            name=op.f("fk_merch_product_variants_product_id_merch_products"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merch_product_variants")),
        sa.UniqueConstraint("club_id", "sku", name="uq_merch_variants_club_sku"),
    )
    op.create_index(
        op.f("ix_merch_product_variants_club_id"),
        "merch_product_variants",
        ["club_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_merch_product_variants_product_id"),
        "merch_product_variants",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_merch_product_variants_sku"), "merch_product_variants", ["sku"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=True),
        sa.Column("cart_id", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("subtotal_cents", sa.Integer(), nullable=False),
        sa.Column("discount_cents", sa.Integer(), nullable=False),
        sa.Column("shipping_cents", sa.Integer(), nullable=False),
        sa.Column("tax_cents", sa.Integer(), nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column("promotion_id", sa.String(length=32), nullable=True),
        sa.Column("payment_id", sa.String(length=32), nullable=True),
        sa.Column("shipping_address_json", sa.JSON(), nullable=False),
        sa.Column("placed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["cart_id"], ["carts.id"], name=op.f("fk_orders_cart_id_carts")),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], name=op.f("fk_orders_club_id_clubs")),
        sa.ForeignKeyConstraint(
            ["promotion_id"], ["promotions.id"], name=op.f("fk_orders_promotion_id_promotions")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index(op.f("ix_orders_club_id"), "orders", ["club_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "play_assignments",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("play_id", sa.String(length=32), nullable=False),
        sa.Column("player_id", sa.String(length=32), nullable=True),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_play_assignments_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["play_id"], ["plays.id"], name=op.f("fk_play_assignments_play_id_plays")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_play_assignments_player_id_players")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_play_assignments")),
    )
    op.create_index(
        op.f("ix_play_assignments_club_id"), "play_assignments", ["club_id"], unique=False
    )
    op.create_index(
        op.f("ix_play_assignments_play_id"), "play_assignments", ["play_id"], unique=False
    )
    op.create_table(
        "player_identities",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("match_id", sa.String(length=32), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.String(length=32), nullable=True),
        sa.Column("jersey_number", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_player_identities_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["match_id"], ["matches.id"], name=op.f("fk_player_identities_match_id_matches")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_player_identities_player_id_players")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_identities")),
    )
    op.create_index(
        op.f("ix_player_identities_club_id"), "player_identities", ["club_id"], unique=False
    )
    op.create_index(
        op.f("ix_player_identities_match_id"), "player_identities", ["match_id"], unique=False
    )
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("match_id", sa.String(length=32), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("celery_task_id", sa.String(length=255), nullable=True),
        sa.Column("params_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=32), nullable=False),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_processing_jobs_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["match_id"], ["matches.id"], name=op.f("fk_processing_jobs_match_id_matches")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_jobs")),
    )
    op.create_index(
        op.f("ix_processing_jobs_club_id"), "processing_jobs", ["club_id"], unique=False
    )
    op.create_index(
        op.f("ix_processing_jobs_match_id"), "processing_jobs", ["match_id"], unique=False
    )
    op.create_index(op.f("ix_processing_jobs_status"), "processing_jobs", ["status"], unique=False)
    op.create_table(
        "registration_documents",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("registration_id", sa.String(length=32), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("doc_type", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("uploaded_by", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_registration_documents_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["registration_id"],
            ["registrations.id"],
            name=op.f("fk_registration_documents_registration_id_registrations"),
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_registration_documents_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registration_documents")),
    )
    op.create_index(
        op.f("ix_registration_documents_club_id"),
        "registration_documents",
        ["club_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registration_documents_registration_id"),
        "registration_documents",
        ["registration_id"],
        unique=False,
    )
    op.create_table(
        "training_attendance",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("plan_id", sa.String(length=32), nullable=False),
        sa.Column("player_id", sa.String(length=32), nullable=False),
        sa.Column("session_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("note", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_training_attendance_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["training_plans.id"],
            name=op.f("fk_training_attendance_plan_id_training_plans"),
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_training_attendance_player_id_players")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_attendance")),
    )
    op.create_index(
        op.f("ix_training_attendance_club_id"), "training_attendance", ["club_id"], unique=False
    )
    op.create_index(
        op.f("ix_training_attendance_plan_id"), "training_attendance", ["plan_id"], unique=False
    )
    op.create_index(
        op.f("ix_training_attendance_player_id"), "training_attendance", ["player_id"], unique=False
    )
    op.create_table(
        "video_assets",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("match_id", sa.String(length=32), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=False),
        sa.Column("fps", sa.Float(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("meta_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_video_assets_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["match_id"], ["matches.id"], name=op.f("fk_video_assets_match_id_matches")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_assets")),
    )
    op.create_index(op.f("ix_video_assets_club_id"), "video_assets", ["club_id"], unique=False)
    op.create_index(op.f("ix_video_assets_match_id"), "video_assets", ["match_id"], unique=False)
    op.create_table(
        "match_events",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("match_id", sa.String(length=32), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("t_start_s", sa.Float(), nullable=False),
        sa.Column("t_end_s", sa.Float(), nullable=False),
        sa.Column("player_identity_id", sa.String(length=32), nullable=True),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("meta_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_match_events_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["match_id"], ["matches.id"], name=op.f("fk_match_events_match_id_matches")
        ),
        sa.ForeignKeyConstraint(
            ["player_identity_id"],
            ["player_identities.id"],
            name=op.f("fk_match_events_player_identity_id_player_identities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match_events")),
    )
    op.create_index(op.f("ix_match_events_club_id"), "match_events", ["club_id"], unique=False)
    op.create_index(
        op.f("ix_match_events_event_type"), "match_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_match_events_match_id"), "match_events", ["match_id"], unique=False)
    op.create_table(
        "order_items",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("order_id", sa.String(length=32), nullable=False),
        sa.Column("product_ref", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("unit_price_cents", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("meta_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_order_items_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_items_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(op.f("ix_order_items_club_id"), "order_items", ["club_id"], unique=False)
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("invoice_id", sa.String(length=32), nullable=True),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("provider_ref", sa.String(length=255), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["club_id"], ["clubs.id"], name=op.f("fk_payments_club_id_clubs")),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["invoices.id"], name=op.f("fk_payments_invoice_id_invoices")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(op.f("ix_payments_club_id"), "payments", ["club_id"], unique=False)
    op.create_index(
        op.f("ix_payments_idempotency_key"), "payments", ["idempotency_key"], unique=True
    )
    op.create_index(op.f("ix_payments_invoice_id"), "payments", ["invoice_id"], unique=False)
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    op.create_table(
        "player_match_stats",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("match_id", sa.String(length=32), nullable=False),
        sa.Column("player_identity_id", sa.String(length=32), nullable=False),
        sa.Column("minutes_tracked", sa.Float(), nullable=False),
        sa.Column("distance_proxy_m", sa.Float(), nullable=False),
        sa.Column("touches", sa.Integer(), nullable=False),
        sa.Column("passes", sa.Integer(), nullable=False),
        sa.Column("tackles", sa.Integer(), nullable=False),
        sa.Column("shots", sa.Integer(), nullable=False),
        sa.Column("turnovers", sa.Integer(), nullable=False),
        sa.Column("scoring_events", sa.Integer(), nullable=False),
        sa.Column("avg_confidence", sa.Float(), nullable=False),
        sa.Column("heatmap_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_player_match_stats_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["match_id"], ["matches.id"], name=op.f("fk_player_match_stats_match_id_matches")
        ),
        sa.ForeignKeyConstraint(
            ["player_identity_id"],
            ["player_identities.id"],
            name=op.f("fk_player_match_stats_player_identity_id_player_identities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_match_stats")),
    )
    op.create_index(
        op.f("ix_player_match_stats_club_id"), "player_match_stats", ["club_id"], unique=False
    )
    op.create_index(
        op.f("ix_player_match_stats_match_id"), "player_match_stats", ["match_id"], unique=False
    )
    op.create_table(
        "upload_records",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("artifact_id", sa.String(length=32), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("platform_video_id", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=512), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tags_json", sa.JSON(), nullable=False),
        sa.Column("category_id", sa.String(length=16), nullable=False),
        sa.Column("privacy", sa.String(length=16), nullable=False),
        sa.Column("error_log_json", sa.JSON(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"], ["artifacts.id"], name=op.f("fk_upload_records_artifact_id_artifacts")
        ),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_upload_records_club_id_clubs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upload_records")),
    )
    op.create_index(op.f("ix_upload_records_club_id"), "upload_records", ["club_id"], unique=False)
    op.create_index(
        op.f("ix_upload_records_idempotency_key"),
        "upload_records",
        ["idempotency_key"],
        unique=True,
    )
    op.create_table(
        "play_clip_links",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("club_id", sa.String(length=32), nullable=False),
        sa.Column("play_id", sa.String(length=32), nullable=False),
        sa.Column("match_event_id", sa.String(length=32), nullable=False),
        sa.Column("note", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["club_id"], ["clubs.id"], name=op.f("fk_play_clip_links_club_id_clubs")
        ),
        sa.ForeignKeyConstraint(
            ["match_event_id"],
            ["match_events.id"],
            name=op.f("fk_play_clip_links_match_event_id_match_events"),
        ),
        sa.ForeignKeyConstraint(
            ["play_id"], ["plays.id"], name=op.f("fk_play_clip_links_play_id_plays")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_play_clip_links")),
    )
    op.create_index(
        op.f("ix_play_clip_links_club_id"), "play_clip_links", ["club_id"], unique=False
    )
    op.create_index(
        op.f("ix_play_clip_links_match_event_id"),
        "play_clip_links",
        ["match_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_play_clip_links_play_id"), "play_clip_links", ["play_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_play_clip_links_play_id"), table_name="play_clip_links")
    op.drop_index(op.f("ix_play_clip_links_match_event_id"), table_name="play_clip_links")
    op.drop_index(op.f("ix_play_clip_links_club_id"), table_name="play_clip_links")
    op.drop_table("play_clip_links")
    op.drop_index(op.f("ix_upload_records_idempotency_key"), table_name="upload_records")
    op.drop_index(op.f("ix_upload_records_club_id"), table_name="upload_records")
    op.drop_table("upload_records")
    op.drop_index(op.f("ix_player_match_stats_match_id"), table_name="player_match_stats")
    op.drop_index(op.f("ix_player_match_stats_club_id"), table_name="player_match_stats")
    op.drop_table("player_match_stats")
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_invoice_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_idempotency_key"), table_name="payments")
    op.drop_index(op.f("ix_payments_club_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_club_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_match_events_match_id"), table_name="match_events")
    op.drop_index(op.f("ix_match_events_event_type"), table_name="match_events")
    op.drop_index(op.f("ix_match_events_club_id"), table_name="match_events")
    op.drop_table("match_events")
    op.drop_index(op.f("ix_video_assets_match_id"), table_name="video_assets")
    op.drop_index(op.f("ix_video_assets_club_id"), table_name="video_assets")
    op.drop_table("video_assets")
    op.drop_index(op.f("ix_training_attendance_player_id"), table_name="training_attendance")
    op.drop_index(op.f("ix_training_attendance_plan_id"), table_name="training_attendance")
    op.drop_index(op.f("ix_training_attendance_club_id"), table_name="training_attendance")
    op.drop_table("training_attendance")
    op.drop_index(
        op.f("ix_registration_documents_registration_id"), table_name="registration_documents"
    )
    op.drop_index(op.f("ix_registration_documents_club_id"), table_name="registration_documents")
    op.drop_table("registration_documents")
    op.drop_index(op.f("ix_processing_jobs_status"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_match_id"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_club_id"), table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index(op.f("ix_player_identities_match_id"), table_name="player_identities")
    op.drop_index(op.f("ix_player_identities_club_id"), table_name="player_identities")
    op.drop_table("player_identities")
    op.drop_index(op.f("ix_play_assignments_play_id"), table_name="play_assignments")
    op.drop_index(op.f("ix_play_assignments_club_id"), table_name="play_assignments")
    op.drop_table("play_assignments")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_club_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_merch_product_variants_sku"), table_name="merch_product_variants")
    op.drop_index(op.f("ix_merch_product_variants_product_id"), table_name="merch_product_variants")
    op.drop_index(op.f("ix_merch_product_variants_club_id"), table_name="merch_product_variants")
    op.drop_table("merch_product_variants")
    op.drop_index(op.f("ix_invoices_status"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_registration_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_club_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_hydration_reminders_player_id"), table_name="hydration_reminders")
    op.drop_index(op.f("ix_hydration_reminders_club_id"), table_name="hydration_reminders")
    op.drop_table("hydration_reminders")
    op.drop_index(op.f("ix_coach_notes_player_id"), table_name="coach_notes")
    op.drop_index(op.f("ix_coach_notes_club_id"), table_name="coach_notes")
    op.drop_table("coach_notes")
    op.drop_index(op.f("ix_cart_items_club_id"), table_name="cart_items")
    op.drop_index(op.f("ix_cart_items_cart_id"), table_name="cart_items")
    op.drop_table("cart_items")
    op.drop_index(op.f("ix_athlete_profiles_player_id"), table_name="athlete_profiles")
    op.drop_index(op.f("ix_athlete_profiles_club_id"), table_name="athlete_profiles")
    op.drop_table("athlete_profiles")
    op.drop_index(op.f("ix_artifacts_match_id"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_kind"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_club_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_club_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_training_plans_club_id"), table_name="training_plans")
    op.drop_table("training_plans")
    op.drop_index(op.f("ix_registrations_status"), table_name="registrations")
    op.drop_index(op.f("ix_registrations_form_id"), table_name="registrations")
    op.drop_index(op.f("ix_registrations_family_group_id"), table_name="registrations")
    op.drop_index(op.f("ix_registrations_club_id"), table_name="registrations")
    op.drop_table("registrations")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_jti"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_plays_parent_play_id"), table_name="plays")
    op.drop_index(op.f("ix_plays_club_id"), table_name="plays")
    op.drop_index(op.f("ix_plays_category"), table_name="plays")
    op.drop_table("plays")
    op.drop_index(op.f("ix_players_team_id"), table_name="players")
    op.drop_index(op.f("ix_players_club_id"), table_name="players")
    op.drop_table("players")
    op.drop_index(op.f("ix_merch_products_slug"), table_name="merch_products")
    op.drop_index(op.f("ix_merch_products_club_id"), table_name="merch_products")
    op.drop_index(op.f("ix_merch_products_category_id"), table_name="merch_products")
    op.drop_table("merch_products")
    op.drop_index(op.f("ix_matches_team_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_club_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_fee_rules_club_id"), table_name="fee_rules")
    op.drop_table("fee_rules")
    op.drop_index(op.f("ix_competition_standings_source_id"), table_name="competition_standings")
    op.drop_index(op.f("ix_competition_standings_club_id"), table_name="competition_standings")
    op.drop_table("competition_standings")
    op.drop_index(op.f("ix_competition_fixtures_source_id"), table_name="competition_fixtures")
    op.drop_index(op.f("ix_competition_fixtures_external_ref"), table_name="competition_fixtures")
    op.drop_index(op.f("ix_competition_fixtures_club_id"), table_name="competition_fixtures")
    op.drop_table("competition_fixtures")
    op.drop_index(op.f("ix_carts_user_id"), table_name="carts")
    op.drop_index(op.f("ix_carts_status"), table_name="carts")
    op.drop_index(op.f("ix_carts_club_id"), table_name="carts")
    op.drop_table("carts")
    op.drop_index(op.f("ix_audit_logs_club_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_webhook_events_provider_event_id"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_club_id"), table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_club_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_training_templates_role"), table_name="training_templates")
    op.drop_index(op.f("ix_training_templates_club_id"), table_name="training_templates")
    op.drop_table("training_templates")
    op.drop_index(op.f("ix_teams_club_id"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_tax_configs_club_id"), table_name="tax_configs")
    op.drop_table("tax_configs")
    op.drop_index(op.f("ix_shipping_configs_club_id"), table_name="shipping_configs")
    op.drop_table("shipping_configs")
    op.drop_index(op.f("ix_registration_forms_club_id"), table_name="registration_forms")
    op.drop_table("registration_forms")
    op.drop_index(op.f("ix_promotions_code"), table_name="promotions")
    op.drop_index(op.f("ix_promotions_club_id"), table_name="promotions")
    op.drop_table("promotions")
    op.drop_index(op.f("ix_merch_categories_slug"), table_name="merch_categories")
    op.drop_index(op.f("ix_merch_categories_club_id"), table_name="merch_categories")
    op.drop_table("merch_categories")
    op.drop_index(op.f("ix_meal_templates_day_type"), table_name="meal_templates")
    op.drop_index(op.f("ix_meal_templates_club_id"), table_name="meal_templates")
    op.drop_table("meal_templates")
    op.drop_index(op.f("ix_coupons_code"), table_name="coupons")
    op.drop_index(op.f("ix_coupons_club_id"), table_name="coupons")
    op.drop_table("coupons")
    op.drop_index(op.f("ix_competition_sources_club_id"), table_name="competition_sources")
    op.drop_index(op.f("ix_competition_sources_adapter_key"), table_name="competition_sources")
    op.drop_table("competition_sources")
    op.drop_index(op.f("ix_club_modules_club_id"), table_name="club_modules")
    op.drop_table("club_modules")
    op.drop_index(op.f("ix_clubs_slug"), table_name="clubs")
    op.drop_table("clubs")
    # ### end Alembic commands ###
